<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/0a4bedb4d5.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../assets/styles/main.css">
    <title>Akinator</title>
    <link rel="icon" type="image/png" href="../assets/images/akinator-favicon.webp">
</head>

<body>
    <header>
        <div class="header">
            <p>Akinator</p>
            <?php if(isset($_SESSION['user_id'])): ?>
                <a href="logout.php" title="Se déconnecter">
                    <i class="fa-solid fa-right-from-bracket"></i>
                </a>
            <?php endif; ?>
        </div>
        <nav>
            <a href="index.php">Accueil</a>
            <?php if(isset($_SESSION['user_id'])): ?>
                <a href="game.php">Jouer</a>
                <a href="account.php">Mon compte</a>
                <a href="logout.php">Déconnexion</a>
            <?php else: ?>
                <a href="connexion.php">Connexion</a>
                <a href="signup.php">Créer un compte</a>
            <?php endif; ?>
        </nav>
    </header>
    <img src="../assets/images/akinator.png" alt="Akinator" class="header-logo">
    
    <main>
        <?php 
        if (isset($template) && !empty($template) && file_exists($template . '.phtml')) {
            include $template . '.phtml';
        } else {
            // Redirection vers la page d'accueil si aucun template n'est défini
            header('Location: index.php');
            exit;
        }
        ?>
    </main>
    
    <footer>
        <p class="footer">
            @2025 - 3W Academy
        </p>
    </footer>
</body>
</html> 