<div class = "main">


<div class="signup">
    
    <h1>Inscription</h1>
    
    <?php if(isset($error)): ?>
        <div style="color: red;"><?= $error ?></div>
    <?php endif; ?>
    
    <div class="container">
        
        <form method="post">
            
            <label for="nickname">Pseudo :</label>
            <input type="text" id="nickname" name="nickname" required>
            
            <label for="email">Email :</label>
            <input type="email" id="email" name="email" required>
            
            <label for="password">Mot de passe :</label>
            <input type="password" id="password" name="password" required>
            <small>Le mot de passe doit contenir au moins 12 caractères, une majuscule, une minuscule, un chiffre et un caractère spécial.</small>
            
            <button type="submit">S'inscrire</button>
            
            <p>Vous avez déjà un compte ? <a href="connexion.php">Se connecter</a></p>
        </form>
        
    </div>
</div>

</div>
    