<div class = "main">


<div class="signup">
    
    <h1>Inscription</h1>
    
    <?php if(isset($error)): ?>
        <div><?= $error ?></div>
    <?php endif; ?>
    
    <div class="container">
        
        <form method="post">
            
            <label for="nickname">Pseudo :</label>
            <input type="text" id="nickname" name="nickname" required>
            
            <label for="email">Email :</label>
            <input type="email" id="email" name="email" required>
    
            <label for="new-password">Mot de passe :</label>
            <input type="password" id="new-password" name="password" required>
    
            <button type="submit">S'inscrire</button>
            
            <p>Vous avez déjà un compte ? <a href="connexion.php">Se connecter</a></p>
        </form>
        
    </div>
</div>

</div>
    